Repository mwrlabs/needle, pull requests merged in 2018-07, with the labels that each got.

#233 Fix syntax issues in the module "script_hook-method-of-class"
  needle/modules/hooking/frida/script_hook-method-of-class.py
Labels: feature/enhancement, loc-module

#236 Fix "program" validate function in "theos_tweak.py"
  needle/modules/hooking/theos/theos_tweak.py
Labels: bug, loc-module

#239 Fix the installation process for installing Theos while using the module 'device/dependency_installer'
  needle/core/utils/constants.py
Labels: bug, feature/enhancement, loc-module

#203 External sshpass command now supports complex passwords
  needle/core/device/device.py
  needle/core/device/remote_operations.py
Labels: dependency, feature/enhancement

#227 Fix Handling of periods in class names - class_dump_frida_enum-all-methods.py
  needle/modules/binary/reversing/class_dump_frida_enum-all-methods.py
Labels: bug, loc-module

#241 Fix Handling of periods in class names - script_hook-all-methods-of-class.py
  needle/modules/hooking/frida/script_hook-all-methods-of-class.py
Labels: bug, loc-module

#228 Fix Handling of periods in class names - class_dump_frida_find-class-enum-methods.py
  needle/modules/binary/reversing/class_dump_frida_find-class-enum-methods.py
Labels: bug, loc-module

#229 Fix how the module "cycript_shell.py" finds running processes via "ps ax | grep"
  needle/modules/hooking/cycript/cycript_shell.py
Labels: bug, loc-module

#230 Fix how the module "cycript_touchid.py" finds running processes via "ps ax | grep"
  needle/modules/hooking/cycript/cycript_touchid.py
Labels: bug, loc-module

#231 Fix how Frida script modules find running processes via "ps ax | grep"
  needle/core/framework/module.py
Labels: bug, loc-module

#237 Fix how the module "heap_dump.py" finds processes via "ps ax | grep"
  needle/modules/dynamic/memory/heap_dump.py
Labels: bug, loc-module
